spring:
  application:
    name: Process File Service
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: C##GEOREFERENCE_PROCESS_FILE
    password: password123
    driver-class-name: oracle.jdbc.OracleDriver
    appregca:
      url: jdbc:oracle:thin:@//192.168.11.86:1530/MULTIDBD
      username: APPREGCA
      password: regul.321DES
      driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 20000000
      pool-name: HikariProcessFile
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    #hibernate:
      #ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        cache:
#          use_query_cache: true
#          use_second_level_cache: true
#          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:schema.sql
# Kafka Settings
  kafka:
    bootstrap-servers: 192.168.112.102:29092
#    consumer:
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
csv:
  file:
    path: classpath:converted.csv
  output:
    file:
      path: C:\\Users\\Administrador\\Documents\\
server:
  address: 0.0.0.0
  port: 2004
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.georeference.controllers

#logging:
#  level:
#    org:
#      springframework:
#        batch: DEBUG
#        batch.core: DEBUG
